[package]
name = "axum-app"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.71"
axum = { version = "0.6.18", features = ["tower-log", "form", "macros", "multipart"] }
axum-template = { version = "0.19.0", features = ["tera"] }
azure_core = "0.12.0"
azure_identity = "0.12.0"
azure_storage = "0.12.0"
azure_storage_blobs = "0.12.0"
futures = "0.3.28"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
tera = "1.19.0"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.4.1", features = ["fs", "trace"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
