[package]
name = "rocket-app"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
azure_core = "0.11.0"
azure_identity = "0.11.0"
rocket = { version = "0.5.0-rc.2", features = ["tls"] }
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"] }
