[package]
name = "rocket-app"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.71"
azure_core = "0.11.0"
azure_identity = "0.11.0"
chrono = { version = "0.4.26", features = ["serde"] }
log = "0.4.19"
reqwest = "0.11.18"
rocket = { version = "0.5.0-rc.2", features = ["tls", "json"] }
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
url = { version = "2.4.0", features = ["serde"] }
uuid = { version = "1.3.4", features = ["serde"] }
